services:
  warbler:
    image: warbler
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 6464:6464
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./dist-server/index.js"]
